Font workshop
sheffieldhackspace/Public-Website pull request #60
Opened 2024-03-10 02:38 UTC by alifeee

Add blog post about font workshop. See preview on <https://shhm.alifeee.co.uk/font-workshop/>

I also added some instructions on the README of how to set up Jekyll locally (on linux). I do not like using Docker on my laptop.

:)

2024-03-13 13:53 UTC, alifeee commented
The preview was actually broken. It is now fixed.

<https://shhm.alifeee.co.uk/font-workshop/>

2024-03-14 20:15 UTC, LouiseMcMahon requested changes

2024-03-14 20:15 UTC, LouiseMcMahon commented on README.md
> -All changes should be made as a pull request to main. All changes require a PR review from one trustee.
Can we revert this change as we want everyone to run using docker to ensure were always testing locally using the same version

2024-03-14 20:23 UTC, LouiseMcMahon approved these changes

2024-03-14 20:23 UTC, merged