add space API json file
sheffieldhackspace/Public-Website pull request #80
Opened 2024-10-28 14:48 UTC by alifeee

please see -> https://spaceapi.io/

> [SpaceAPI is] A standardized JSON file that can be used to expose information about hackerspaces, makerspaces, fablabs, chaostreffs and the like across the world to web apps or any other application. 

for now it is just a static file with information about the space

it would be neat if it was active and had live-data about [space open-ness (either calendar-based or connected to the MQTT door system)] / [webcams] / [sensors] / [events], as many other hackspaces do (see <https://api.fablab-nuernberg.de/spaceapi.php> e.g., or many others on <https://directory.spaceapi.io/>), but previous discussions about open data make me think that this idea would not be well adopted. So, for now, it is static and not networked.

after this PR, one should be made to add the URL to the directory on <https://github.com/SpaceApi/directory>

thanks

2024-10-28 14:49 UTC, alifeee commented
see what it would look like on this test site -> <https://api.fablab-nuernberg.de/spaceapi.php>

2024-10-28 18:34 UTC, LouiseMcMahon requested changes
Can you generate the file from the _config.my and add any bits that you don’t have that are missing to the config or a data file.

Could you also check that anything you add to the config isn’t duplicated else where and also uses the confg.

I can just see this file getting forgotten about and then not being updated.

2024-10-29 14:14 UTC, alifeee commented
yes, that's a good idea. I agree.

I moved everything bar the link to the wiki, as it didn't seem incredibly apt. To be honest, I could argue for just removing it. I may do so now.

2024-11-07 21:24 UTC, LouiseMcMahon requested changes

2024-11-07 21:24 UTC, LouiseMcMahon commented on _config.yml
> +    value: 6
Could we pull these into the joining page? Doesn't need to be complex. Just so if someone goes to update prices they wont miss one place or the other.

2024-11-07 21:24 UTC, LouiseMcMahon commented on _config.yml
> +latitude: 53.369933
Can we use these in the osm.html file please

2024-11-08 18:01 UTC, alifeee commented
I have done so

see on <https://shhm-spaceapi-preview.surge.sh/joining/>

![image](https://github.com/user-attachments/assets/424e4c9d-6dd0-4c06-9f53-7eaf3a5c732c)

2024-11-08 19:09 UTC, LouiseMcMahon approved these changes

2024-11-08 19:44 UTC, merged

2024-11-08 19:52 UTC, alifeee commented
lovely thank you -> https://github.com/SpaceApi/directory/pull/269